### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by filoor** [athombv/nl.eneco.toon#1]
How can i install this on my homey?

**Comment by RobinBol** [comment]
Unfortunately you can't yet, it is still a work in progress!

**Comment by filoor** [comment]
And the nest app?

**Comment by RobinBol** [comment]
We are about to launch a small pilot for about 50 users!

**Comment by filoor** [comment]
Can I join the pilot have 1 nest 2 nest protect's and a nest cam

**Comment by RobinBol** [comment]
Unfortunately I have no say in who gets to participate, its first come first serve. But I will notify you once the pilot starts!

**Comment by filoor** [comment]
thanx

**Comment by mvunen** [comment]
Can I join for the Toon beta program when its ready? 
Thanks....

**Comment by RobinBol** [comment]
Not sure if there will be a beta program, if that would be the case I'd let you know.

**Comment by opdoffer** [comment]
When will this app be released in the atom store? Any insights on that?
