### ISSUE TITLE
Issue with login

### ISSUE THREAD

**Issue by chrisboer** [athombv/nl.eneco.toon#11]
I think something changed in 1.05 with regards to userid and password because I think the API needs a request with email address and I only type in a username and password as email address and password does not let me add my TOON. 

Because after some time the token needs to be renewed and this seems to happen with the email address and not with only a username.

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&username=<email address>&password=<password>&client_id=<key>&client_secret=<secret>" https://api.toonapi.com/token

**Comment by RobinBol** [comment]
Hi Chris, thanks for reporting your issue. Nothing changed with regard to the username or password. The app uses OAuth2 which leaves all the complicated login stuff at Toon's responsibility (not the Toon app for Homey). You login on the Toon API and then the Toon app receives a token which can be used to refresh the authentication (so we don't need your login credentials to do so), if the login does not work for you it is very likely that you are not using the right credentials (this is outside our control). Please not that the Toon API login NEEDS your email adres and NOT your username.
