### ISSUE TITLE
Toon

### ISSUE THREAD

**Issue by PeterBox** [athombv/nl.eneco.toon#13]
After a voice command Toon app does not return to set program

**Comment by RobinBol** [comment]
What voice command did you use, to do what?

**Comment by PeterBox** [comment]
This is the flow i use 
![toon](https://cloud.githubusercontent.com/assets/20737747/23521777/baa5619e-ff80-11e6-9a65-d904f6d97538.jpg)

**Comment by RobinBol** [comment]
Ok thanks, well as you can see the Flow gives an error; 503 meaning that the Toon API is throttling you out. This is not something we can fix, it is a known issue for the Toon API guys but nu solution as of yet.

**Comment by PeterBox** [comment]
Strange because it worked  before,  and after the last update  it doesn't

**Comment by RobinBol** [comment]
Not related to the app update, it is really the Toon API that is unavailable in this case. It's availability is changing like the weather..

**Comment by PeterBox** [comment]
Ok thx for your response
