### ISSUE TITLE
"Stel temperatuur stand in" activates program

### ISSUE THREAD

**Issue by Spaapen** [athombv/nl.eneco.toon#15]
When i use the card "Stel temperatuur stand in" to "Slapen" is doesn't activate the predifined setting but activateds the next program. Progam is nomally turned off.
Before the last 2 updates this behaviour didn't happen, it just immediaty set the temperature to "Slapen" whitout activating the program.

**Comment by RobinBol** [comment]
Thanks for letting us know! We tried to improve this behavior such that the program would resume after a user performs a state change. It appears that the api call for resuming the program after a change is rather unstable and caused the state change to fail for some users, for now I have reverted this (so the state change should work, however without resuming program afterwards) as we are dependent on the Toon API for this.
