### ISSUE TITLE
Temperature not set even when Homey says it sets temperature

### ISSUE THREAD

**Issue by HansieNL** [athombv/nl.eneco.toon#19]
What is your Homey version (Settings ? System)?

1.2

What did you try to achieve?

Set Toon thermostat to a higher temperature.

What was the result?

I said: "It's cold" and Homey asked to set the thermostat a degree higher. I confirmed, but nothing happened. I tried again and confirmed. Temperature was set 2 degrees higher.

What did you expect as result?

Homey sets temperature when Homey says it sets temperatur. 

Any other remarks

Looks like command is not triggered right away. Problem confirmed by other forum member.

**Comment by RobinBol** [comment]
Again probably caused by the unreliable Toon API.

**Comment by HansieNL** [comment]
It's working now. I'll close the issue.
