### ISSUE TITLE
Toon error message when reconnecting toon

### ISSUE THREAD

**Issue by chrisboer** [athombv/nl.eneco.toon#20]
Reinstalled toon because it is a beta app and toon got disconnected again.

Now I get an error message when login to mijneneco

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/25221783/a211c814-25b6-11e7-9bb2-48fc687faa66.png)

**Comment by arno1965** [comment]
Same problem here. 2 error messages when installing the Toon app: 1st "__error__"  2nd "missing code"

**Comment by daneedk** [comment]
Same here, On every firmware update I have to remove and reinstall the Toon app en connect my Toon. 
This time it fails:
1st error:
![image](https://cloud.githubusercontent.com/assets/16610696/25246771/f75f24fe-2608-11e7-91c6-ec217a7a5ce1.png)
2nd error
![image](https://cloud.githubusercontent.com/assets/16610696/25246812/1ad3f414-2609-11e7-985e-8e055e08da5b.png)

**Comment by ricksulman** [comment]
I can confirm this bug on 1.2.2

**Comment by RobinBol** [comment]
Thanks for reporting, we are working with the people from Toon to resolve this.

**Comment by chrisboer** [comment]
After leaving the HOMEY off power all night I tried to reconnect toon again this morning and it works so Toon is available again without errors.

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/25421852/f8fe6df6-2a5e-11e7-8b01-62c746561a93.png)

**Comment by Spaapen** [comment]
I can confirm that the Toon connection works again at the moment.

**Comment by daneedk** [comment]
Here it's working again too.

**Comment by arno1965** [comment]
Yes working again.

**Comment by rtnartna** [comment]
Also working again over here.

**Comment by DeefK** [comment]
Working again.

**Comment by chrisboer** [comment]
Again issues with Toon disconnected
