### ISSUE TITLE
Connect Error: 'missing agreementId'

### ISSUE THREAD

**Issue by RRoelof** [athombv/nl.eneco.toon#22]
On previous issues a reset worked, but this one stays persistent. I've managed to get a response from Quby, but they claim the API is working ok from their end.

![homeytoonerror](https://user-images.githubusercontent.com/25590277/28257144-bef03482-6ac8-11e7-87ef-6c4bb28b631c.jpeg)

Any suggestions on how to tackle this?

**Comment by mtrams** [comment]
Same error here

**Comment by Spaapen** [comment]
And also the same here

**Comment by RobinBol** [comment]
This error should be fixed in the latest Toon app update. Could you verify this is the case?

**Comment by mtrams** [comment]
Toon is working again. Thanks!

**Comment by RobinBol** [comment]
@RRoelof do you experience the same?

**Comment by Spaapen** [comment]
Works here too!

**Comment by RRoelof** [comment]
@RobinBol - Back in business again, thnX!

**Comment by RobinBol** [comment]
Great!
