### ISSUE TITLE
Connection Toon every week gone

### ISSUE THREAD

**Issue by MarcelS1988** [athombv/nl.eneco.toon#23]
Every week is the connection of Toon gone.

I have to delete it, than I have to restart it at the apps, than I can install it again.
End than it is avaible for 1 week, than it is again gone.

**Comment by Veldkornet** [comment]
Same here, really annoying.
Then you have to re-create all of the flows as well.

**Comment by RobinBol** [comment]
There has been an update to the Toon app, could you check if this issue is resolved for now? Maybe re-add Toon once, then it should not lose its connection anymore.

**Comment by daneedk** [comment]
The app was just updated to 1.2.4, Toon still there! 2 out of 2, way to go!

**Comment by Veldkornet** [comment]
Everything was going good, but today I did a reboot of Homey, and now Toon's temperature no longer shows.

- I tried to remove the device (and if you try add it again, it doesn't show, so you need to remove the app too)
- Re-installed the app
- Can't login anymore, just get a blank white screen

Toon API down? Or something else?

**Comment by RobinBol** [comment]
Yes Toon API is down.

**Comment by RobinBol** [comment]
Hi all, from the responses in the app store to the latest app update I can say that this issue is fixed, hence I will close it. If for some reason this issue is not solved for you, please place a comment with some information so we can re-open if necessary. Thanks for reporting!
