### ISSUE TITLE
Aanmelden Toon

### ISSUE THREAD

**Issue by PeterBox** [athombv/nl.eneco.toon#26]
I get this message when i want to connect with Toon 

Deze site is niet bereikbaar

De webpagina op https://api.toonapi.com/authorize?response_type=code&client_id=vLemcczaqq6dUZeo7hzjRBBYAfka&redirect_uri=https://callback.athom.com/oauth2/callback/ is mogelijk tijdelijk uitgeschakeld of permanent verplaatst naar een nieuw webadres.
ERR_SSL_UNRECOGNIZED_NAME_ALERT

**Comment by RobinBol** [comment]
The Toon API is currently down, not something we can fix unfortunately.

**Comment by PeterBox** [comment]
ok then we have to wait again

**Comment by RobinBol** [comment]
This should have been resolved automatically a while back, if not please let me know.
