### ISSUE TITLE
Even If setting is out of range Homey respond with setting done, but nothing is set

### ISSUE THREAD

**Issue by HansieNL** [athombv/nl.eneco.toon#8]
What is your Homey version (Settings → System)?

1.1.4

What did you try to achieve?

Set Toon thermostat to a higher temperature than 30 degrees.

What was the result?

Homey response with: "Thermostat is set to 32 degrees", but nothing is set. Setting is limited from 6 till 30 in the app, so setting is out of range.

That did you expect as result?

If a setting is out of range a clear warning would be welcome. I expect an answer like: "Your setting is not allowed. You can set a temperature between 6 and 30 degrees".

Any other remarks

Same happens with ThermoSmart app.

**Comment by bvdbos** [comment]
Happens the same on Thermosmart... https://github.com/athombv/nl.thermosmart

**Comment by RobinBol** [comment]
How do you set the thermostat higher than the limit? Mobile card, flow, speech?

**Comment by HansieNL** [comment]
I tried via speech.

**Comment by RobinBol** [comment]
Thanks for reporting this issue, I forwarded it to the person responsible for the speech implementation and this will be fixed in a future Homey firmware update.

**Comment by Tweake** [comment]
Just added a fix which will be included in the Homey 1.2.0 update.
